# Generated by Django 3.1.4 on 2020-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(max_length=20)),
                ('etype', models.CharField(max_length=100)),
                ('etitle', models.CharField(max_length=100)),
                ('eauthor', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
